name: abagon_dao
version: 0.1.0
author: eldardo.org
description: A library to encapsulate DAO implementations so that changing underlying DB is not a pain.
dev_dependencies:
  unittest: any

#dependencies:
#  unittest: any